export interface PropertyCatalogImage {
  id: string;
  propertyId: string;
  url: string;
  isPrimary: number;
  displayOrder: number;
  category: string;
  caption: string;
}

// Full photographic dataset for properties prop_01 to prop_06
export const BATCH_1_IMAGES: PropertyCatalogImage[] = [
  // prop_01: The Azure Vista Contemporary Villa in Cinnamon Gardens (VILLA, Colombo 07)
  {
    id: 'img_p01_01',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Main front exterior of the contemporary tropical villa with private lap pool and manicured courtyard',
  },
  {
    id: 'img_p01_02',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Double-height open living pavilion with polished Kumbuk timber flooring and floor-to-ceiling glass',
  },
  {
    id: 'img_p01_03',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'DINING_AREA',
    caption: 'Formal 10-seater solid teak dining table overlooking internal landscaped courtyard',
  },
  {
    id: 'img_p01_04',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Custom teak chef kitchen with white quartz waterfall island and imported European appliances',
  },
  {
    id: 'img_p01_05',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Spacious master suite featuring wide-plank teak floors, king bed, and private tropical garden terrace',
  },
  {
    id: 'img_p01_06',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Light-filled second bedroom with custom integrated teak wardrobes and acoustic double glazing',
  },
  {
    id: 'img_p01_07',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Master ensuite with Italian marble finishes, freestanding soaking tub, and rainfall shower',
  },
  {
    id: 'img_p01_08',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SWIMMING_POOL',
    caption: 'Private 40ft freshwater lap pool with sun loungers surrounded by lush frangipani and traveler palms',
  },
  {
    id: 'img_p01_09',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'OUTDOOR_GARDEN',
    caption: 'Landscaped central courtyard garden with outdoor teak seating and tropical greenery',
  },
  {
    id: 'img_p01_10',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Covered 3-car executive garage with automated roller shutter gate and EV charging point',
  },
  {
    id: 'img_p01_11',
    propertyId: 'prop_01',
    url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'FEATURE_IMAGE',
    caption: 'Temperature-controlled glass wine gallery and private tasting lounge',
  },

  // prop_02: Havelock City Sky Penthouse Residence (CONDO, Colombo 05)
  {
    id: 'img_p02_01',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Panoramic skyline view of the duplex sky penthouse residence in Havelock City',
  },
  {
    id: 'img_p02_02',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Grand living room featuring 14-foot beamed ceilings and floor-to-ceiling city skyline glass',
  },
  {
    id: 'img_p02_03',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'DINING_AREA',
    caption: 'Open penthouse dining suite with designer bronze pendant lighting and Colombo sunset views',
  },
  {
    id: 'img_p02_04',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Custom lacquer kitchen with waterfall granite breakfast island and integrated appliances',
  },
  {
    id: 'img_p02_05',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Master bedroom suite with wrap-around corner glass overlooking the Indian Ocean and city',
  },
  {
    id: 'img_p02_06',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Second bedroom with warm hardwood finishes and private en-suite access',
  },
  {
    id: 'img_p02_07',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Designer bathroom with walk-in thermostatic rain shower and floating vanity',
  },
  {
    id: 'img_p02_08',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'ROOFTOP_TERRACE',
    caption: 'Private duplex rooftop terrace with outdoor BBQ pavilion and coastline views',
  },
  {
    id: 'img_p02_09',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'FITNESS_CENTER',
    caption: 'Havelock City residents fitness club with high-end cardio and strength training equipment',
  },
  {
    id: 'img_p02_10',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'SWIMMING_POOL',
    caption: 'Resort-style outdoor swimming pool and sun deck within the private gated complex',
  },
  {
    id: 'img_p02_11',
    propertyId: 'prop_02',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'PARKING_GARAGE',
    caption: 'Dedicated underground basement parking bays with high-speed elevator access to penthouse',
  },

  // prop_03: Bolgoda Modern Waterfront Estate (HOUSE, Moratuwa)
  {
    id: 'img_p03_01',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Waterfront estate exterior on the shores of Bolgoda Lake with private dock and timber deck',
  },
  {
    id: 'img_p03_02',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Lake-facing living pavilion with folding glass doors connecting to covered verandas',
  },
  {
    id: 'img_p03_03',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'DOUBLE_HEIGHT_FOYER',
    caption: 'Dramatic double-height entry foyer with custom floating timber staircase',
  },
  {
    id: 'img_p03_04',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Modern open kitchen with teak pantry cabinets, granite tops, and garden pass-through',
  },
  {
    id: 'img_p03_05',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Upper-level master bedroom with balcony providing serene water views over Bolgoda Lake',
  },
  {
    id: 'img_p03_06',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Spacious secondary bedroom with natural ventilation and hardwood floors',
  },
  {
    id: 'img_p03_07',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Resort bathroom with sunken stone soaking tub and tropical courtyard outlook',
  },
  {
    id: 'img_p03_08',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SWIMMING_POOL',
    caption: 'Resort-style freshwater lap pool overlooking tranquil lake waters and tropical palms',
  },
  {
    id: 'img_p03_09',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'FEATURE_IMAGE',
    caption: 'Private 60-foot deep-water yacht jetty and lakeside boat mooring',
  },
  {
    id: 'img_p03_10',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Paved circular driveway and covered double garage with remote security gate',
  },
  {
    id: 'img_p03_11',
    propertyId: 'prop_03',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'OUTDOOR_GARDEN',
    caption: 'Broad covered verandas and lakeside lawn with mature coconut trees',
  },

  // prop_04: Mount Lavinia Coastal Luxury Apartment (APARTMENT, Colombo District)
  {
    id: 'img_p04_01',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Modern coastal apartment building on Hotel Road, steps from Mount Lavinia golden beach',
  },
  {
    id: 'img_p04_02',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1502005229762-ee1b2b80a562?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Bright living room with floor-to-ceiling sliding glass doors opening to coastal breeze balcony',
  },
  {
    id: 'img_p04_03',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'BALCONY_VIEW',
    caption: 'Private viewing balcony offering Indian Ocean sunsets and coastal promenade vistas',
  },
  {
    id: 'img_p04_04',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Modern designer kitchen with polished granite waterfall island and induction cooktop',
  },
  {
    id: 'img_p04_05',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Acoustically soundproofed master bedroom with walk-in wardrobe and ambient lighting',
  },
  {
    id: 'img_p04_06',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Comfortable guest bedroom with natural daylight and built-in wardrobes',
  },
  {
    id: 'img_p04_07',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Contemporary bathroom with frameless glass walk-in shower and stone vanity',
  },
  {
    id: 'img_p04_08',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'DINING_AREA',
    caption: 'Open dining space connecting seamlessly with living area and kitchen',
  },
  {
    id: 'img_p04_09',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'FITNESS_CENTER',
    caption: 'Residents fitness gym and sauna with modern conditioning equipment',
  },
  {
    id: 'img_p04_10',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'ROOFTOP_LOUNGE',
    caption: 'Shared rooftop observation lounge with 360-degree ocean and Colombo coastal views',
  },
  {
    id: 'img_p04_11',
    propertyId: 'prop_04',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'PARKING_GARAGE',
    caption: 'Dedicated basement parking bay with integrated private electric vehicle (EV) charging point',
  },

  // prop_05: Peradeniya Royal Valley Modern Farmhouse (HOUSE, Kandy)
  {
    id: 'img_p05_01',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Magnificent modern farmhouse residence overlooking the lush Mahaweli River valley in Kandy',
  },
  {
    id: 'img_p05_02',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Expansive living room with exposed timber trusses, natural stone accents, and valley views',
  },
  {
    id: 'img_p05_03',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'WRAPAROUND_VERANDAH',
    caption: 'Broad covered timber verandah capturing cool hill-country breezes and mountain vistas',
  },
  {
    id: 'img_p05_04',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Farmhouse chef kitchen with solid timber cabinetry, central island, and modern gas range',
  },
  {
    id: 'img_p05_05',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Master bedroom suite with vaulted wood ceiling, hardwood floors, and private balcony',
  },
  {
    id: 'img_p05_06',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Second bedroom with garden windows looking out to 2.5 acres of manicured estate grounds',
  },
  {
    id: 'img_p05_07',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Freestanding soaking tub and stone-tiled rain shower with tropical garden view',
  },
  {
    id: 'img_p05_08',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SWIMMING_POOL',
    caption: 'Sparkling swimming pool with sun shelf overlooking the green Peradeniya mountain slopes',
  },
  {
    id: 'img_p05_09',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'GUEST_CASITA',
    caption: 'Detached 1-bedroom private guest casita situated on the estate lawn',
  },
  {
    id: 'img_p05_10',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'OUTDOOR_GARDEN',
    caption: '2.5 acres of manicured tropical grounds, fruit trees, and flowering borders',
  },
  {
    id: 'img_p05_11',
    propertyId: 'prop_05',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'PARKING_GARAGE',
    caption: 'Covered vehicle portico and stone parking area accommodating 4 vehicles',
  },

  // prop_06: World Trade Center Commercial Headquarters Suite (COMMERCIAL, Colombo Fort)
  {
    id: 'img_p06_01',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Twin glass towers of World Trade Center Colombo Fort in the central financial district',
  },
  {
    id: 'img_p06_02',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'RECEPTION_LOBBY',
    caption: 'High-security corporate reception lobby with polished marble and access control turnstiles',
  },
  {
    id: 'img_p06_03',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'BOARDROOM',
    caption: 'Executive boardroom equipped with telepresence AV, motorized blinds, and 20-seat table',
  },
  {
    id: 'img_p06_04',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'OPEN_WORKSPACE',
    caption: 'Flexible open floor plan accommodating 80+ workstations with dual high-speed fiber drops',
  },
  {
    id: 'img_p06_05',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'EXECUTIVE_SUITE',
    caption: 'Corner executive suite with panoramic glass overlooking Colombo Port City and harbor',
  },
  {
    id: 'img_p06_06',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'MEETING_ROOM',
    caption: 'Acoustically insulated private glass meeting suite for executive consultations',
  },
  {
    id: 'img_p06_07',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BREAKOUT_PANTRY',
    caption: 'Corporate employee cafe and pantry with barista station and dining seating',
  },
  {
    id: 'img_p06_08',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SERVER_ROOM',
    caption: 'Climate-controlled dedicated server room with backup generator feeds and fire suppression',
  },
  {
    id: 'img_p06_09',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'BATHROOM',
    caption: 'Executive multi-stall commercial restroom facilities with granite and touchless fixtures',
  },
  {
    id: 'img_p06_10',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Secure executive basement parking bays with direct access to high-speed lifts',
  },
  {
    id: 'img_p06_11',
    propertyId: 'prop_06',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'FEATURE_IMAGE',
    caption: 'High-floor aerial vista of Colombo Harbor, Port City, and the Indian Ocean',
  },
];
