import { PropertyCatalogImage } from './propertyImageCatalog.js';

// Photographic dataset for properties prop_sl_07 to prop_sl_12
export const BATCH_4_IMAGES: PropertyCatalogImage[] = [
  // prop_sl_07: Traditional Ceylon Planter's Bungalow in Kandy (HOUSE, Kandy)
  {
    id: 'img_psl07_01',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Classic colonial tea planter bungalow surrounded by 35 perches of tea gardens on Hanthana Mountain',
  },
  {
    id: 'img_psl07_02',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'EXPANSIVE_VERANDAH',
    caption: 'Broad colonial verandah with white timber pillars, antique planter chairs, and mountain breezes',
  },
  {
    id: 'img_psl07_03',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'DRAWING_ROOM',
    caption: 'Colonial drawing room with functioning red-brick fireplace and polished jackwood flooring',
  },
  {
    id: 'img_psl07_04',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'DINING_ROOM',
    caption: 'Heritage dining hall with 10-seater antique mahogany dining table and garden windows',
  },
  {
    id: 'img_psl07_05',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Planter master suite with authentic four-poster canopy bed, fireplace, and private verandah',
  },
  {
    id: 'img_psl07_06',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'High-ceiling guest bedroom with twin colonial beds and floral draperies',
  },
  {
    id: 'img_psl07_07',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Freestanding cast iron clawfoot tub and traditional brass fittings in heritage bathroom',
  },
  {
    id: 'img_psl07_08',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'KITCHEN',
    caption: 'Spacious country kitchen with solid timber cabinetry and natural mountain spring water tap',
  },
  {
    id: 'img_psl07_09',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'TEA_GARDEN',
    caption: '35 perches of landscaped estate grounds with mature tea bushes and flowering rhododendrons',
  },
  {
    id: 'img_psl07_10',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'MOUNTAIN_PANORAMA',
    caption: 'Panoramic view looking across the mist-shrouded peaks of the Hanthana mountain range',
  },
  {
    id: 'img_psl07_11',
    propertyId: 'prop_sl_07',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'PARKING_PORCH',
    caption: 'Covered colonial vehicle portico and stone parking area accommodating 3 vehicles',
  },

  // prop_sl_08: Commercial Corporate Headquarters Building in Kurunegala (COMMERCIAL, Kurunegala)
  {
    id: 'img_psl08_01',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Modern 3-story commercial headquarters building on Colombo Road, Kurunegala with glass facade',
  },
  {
    id: 'img_psl08_02',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'GROUND_SHOWROOM',
    caption: 'High-visibility column-free ground floor commercial showroom with polished vitrified tiles',
  },
  {
    id: 'img_psl08_03',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'BOARDROOM',
    caption: 'Executive 16-person conference boardroom with acoustic wall paneling and presentation AV',
  },
  {
    id: 'img_psl08_04',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'OPEN_OFFICE',
    caption: 'Spacious second-floor open workstation floor suitable for 40+ staff members',
  },
  {
    id: 'img_psl08_05',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'DIRECTOR_OFFICE',
    caption: 'Corner executive suite with private consultation area and city street view',
  },
  {
    id: 'img_psl08_06',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'ELEVATOR_LOBBY',
    caption: 'Stainless steel passenger elevator and polished granite lobby servicing all floors',
  },
  {
    id: 'img_psl08_07',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Separate male and female commercial restroom facilities on every floor',
  },
  {
    id: 'img_psl08_08',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'POWER_GENERATOR',
    caption: 'Dedicated 3-phase 60A electrical panel and heavy-duty standby generator enclosure',
  },
  {
    id: 'img_psl08_09',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'BASEMENT_PARKING',
    caption: 'Secure underground parking garage with space for 10 vehicles and delivery access',
  },
  {
    id: 'img_psl08_10',
    propertyId: 'prop_sl_08',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'STREET_FRONTAGE',
    caption: 'Prime high-visibility frontage on Colombo Road, Kurunegala with customer parking',
  },

  // prop_sl_09: Beachside Coastal Villa in Polhena, Matara (VILLA, Matara)
  {
    id: 'img_psl09_01',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Two-story tropical beach villa just 80 meters from Polhena Beach with 30ft private pool',
  },
  {
    id: 'img_psl09_02',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'SWIMMING_POOL',
    caption: '30-foot freshwater swimming pool and timber sun deck shaded by tall coconut palms',
  },
  {
    id: 'img_psl09_03',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'LIVING_LOUNGE',
    caption: 'Open-concept beachside living lounge seamlessly extending onto the swimming pool terrace',
  },
  {
    id: 'img_psl09_04',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'BBQ_PAVILION',
    caption: 'Covered garden pavilion with built-in barbecue grill and al fresco teak dining table',
  },
  {
    id: 'img_psl09_05',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'KITCHEN',
    caption: 'Modern open kitchen with teak cabinets, breakfast bar, and stainless steel cooktop',
  },
  {
    id: 'img_psl09_06',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'MASTER_BEDROOM',
    caption: 'Upper-floor master suite with private viewing balcony overlooking the coconut grove and pool',
  },
  {
    id: 'img_psl09_07',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'SECOND_BEDROOM',
    caption: 'Ground-floor guest bedroom with direct garden access and private attached bathroom',
  },
  {
    id: 'img_psl09_08',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'BATHROOM',
    caption: 'Tropical semi-open bathroom with natural pebble floor, rain shower, and solar hot water',
  },
  {
    id: 'img_psl09_09',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'BEACH_PATHWAY',
    caption: 'Direct 80-meter walking lane leading to the calm swimming waters of Polhena coral reef',
  },
  {
    id: 'img_psl09_10',
    propertyId: 'prop_sl_09',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Secure gated vehicle parking area for 3 cars with high perimeter masonry security wall',
  },

  // prop_sl_10: Contemporary Seaside Apartment in Dehiwala (APARTMENT, Colombo District)
  {
    id: 'img_psl10_01',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Contemporary seaside apartment building on Station Road, Dehiwala near the beach and railway',
  },
  {
    id: 'img_psl10_02',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1502005229762-ee1b2b80a562?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Comfortable living area with ceramic porcelain tiling and sliding doors to ocean breeze balcony',
  },
  {
    id: 'img_psl10_03',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'PRIVATE_BALCONY',
    caption: 'Private viewing balcony offering Indian Ocean sunsets and refreshing coastal breezes',
  },
  {
    id: 'img_psl10_04',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'FITTED_KITCHEN',
    caption: 'Fitted kitchen with polished granite worktops, teak veneer cabinetry, and stainless steel sink',
  },
  {
    id: 'img_psl10_05',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Master bedroom with large window, fitted wardrobe, and attached bathroom with hot water',
  },
  {
    id: 'img_psl10_06',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Second bedroom with twin beds, natural lighting, and built-in storage closets',
  },
  {
    id: 'img_psl10_07',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Clean tiled bathroom with hot water shower cubicle and contemporary sanitary fixtures',
  },
  {
    id: 'img_psl10_08',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'DINING_NOOK',
    caption: 'Practical dining nook positioned between living room and kitchen pantry',
  },
  {
    id: 'img_psl10_09',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'ROOFTOP_TERRACE',
    caption: 'Shared resident rooftop terrace with panoramic coastal and city views',
  },
  {
    id: 'img_psl10_10',
    propertyId: 'prop_sl_10',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Allocated covered ground-level parking space with automated security barrier and CCTV',
  },

  // prop_sl_11: Fertile Coconut Estate & Development Land in Negombo (LAND, Gampaha)
  {
    id: 'img_psl11_01',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: '40-perch fertile coconut estate in Kochchikade, Negombo with 28 mature palm trees',
  },
  {
    id: 'img_psl11_02',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'COCONUT_PALMS',
    caption: 'High-yielding king coconut and commercial coconut palms on well-drained sandy loam soil',
  },
  {
    id: 'img_psl11_03',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'ACCESS_ROAD',
    caption: '15-foot wide paved residential access road leading up to the estate entrance',
  },
  {
    id: 'img_psl11_04',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'TUBE_WELL',
    caption: 'Deep tube well providing fresh perennial sweet water with electric pump installation',
  },
  {
    id: 'img_psl11_05',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'BOUNDARY_WALL',
    caption: 'Surveyed concrete boundary posts and partial masonry wall defining the perimeter',
  },
  {
    id: 'img_psl11_06',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'BUILDING_FOOTPRINT',
    caption: 'Naturally cleared central plateau area ready for custom residential villa construction',
  },
  {
    id: 'img_psl11_07',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'SURROUNDINGS',
    caption: 'Tranquil green suburban neighborhood only 12 minutes from the Negombo beach tourist strip',
  },
  {
    id: 'img_psl11_08',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'POWER_CONNECTION',
    caption: 'Nearby CEB electricity transformer pole for immediate single-phase or three-phase connection',
  },
  {
    id: 'img_psl11_09',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1524813686514-a57563d77d66?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'SURVEY_PLAN',
    caption: 'Licensed surveyor boundary plan with First Class clear freehold deeds ready for bank mortgage',
  },
  {
    id: 'img_psl11_10',
    propertyId: 'prop_sl_11',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'HIGHWAY_GATEWAY',
    caption: 'Rapid 20-minute road access to Bandaranaike International Airport (Katunayake) and expressway',
  },

  // prop_sl_12: Colonial Heritage Residence in Chundikuli, Jaffna (HOUSE, Jaffna)
  {
    id: 'img_psl12_01',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Stately traditional northern heritage residence standing on 15 perches in Chundikuli, Jaffna',
  },
  {
    id: 'img_psl12_02',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'PILLARED_VERANDAH',
    caption: 'Grand shaded front verandah with traditional masonry pillars and red-oxide floor finish',
  },
  {
    id: 'img_psl12_03',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'MUTTRAM_COURTYARD',
    caption: 'Traditional open-to-sky central cooling courtyard (Muttram) with ornate carved timber frames',
  },
  {
    id: 'img_psl12_04',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'LIVING_HALL',
    caption: 'Spacious central living hall with 14-foot timber ceilings and solid teak furnishings',
  },
  {
    id: 'img_psl12_05',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Heritage master bedroom suite with authentic louvered shutters and traditional teak wardrobe',
  },
  {
    id: 'img_psl12_06',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Airy guest bedroom with cross-ventilation and views out to the private mango orchard',
  },
  {
    id: 'img_psl12_07',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Modernized bathroom with walk-in shower cubicle, hot water geyser, and brass hardware',
  },
  {
    id: 'img_psl12_08',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'KITCHEN',
    caption: 'Heritage Jaffna kitchen with traditional masonry hearth and modern gas cooking installation',
  },
  {
    id: 'img_psl12_09',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'LIMESTONE_WELL',
    caption: 'Deep traditional coral limestone sweet water well with electric pump providing unlimited water',
  },
  {
    id: 'img_psl12_10',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'MANGO_GARDEN',
    caption: 'Fertile red soil garden planted with mature Karthacolomban mango, palmyrah, and neem trees',
  },
  {
    id: 'img_psl12_11',
    propertyId: 'prop_sl_12',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'WALLED_GATE',
    caption: 'High perimeter security wall and traditional wrought iron entrance gate on Kandy Road',
  },
];
