import { PropertyCatalogImage } from './propertyImageCatalog.js';

// Photographic dataset for properties prop_sl_01 to prop_sl_06
export const BATCH_3_IMAGES: PropertyCatalogImage[] = [
  // prop_sl_01: Modern 3-Bedroom Architect Residence in Nugegoda (HOUSE, Colombo District)
  {
    id: 'img_psl01_01',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Modern two-story architect-designed family residence on 8.5 perches in Nugegoda',
  },
  {
    id: 'img_psl01_02',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Airy open-plan living room with polished porcelain tile flooring and recessed LED lighting',
  },
  {
    id: 'img_psl01_03',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'DINING_AREA',
    caption: 'Dining area opening directly toward internal landscaped courtyard lightwell',
  },
  {
    id: 'img_psl01_04',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Custom solid teak pantry cupboards with black galaxy granite countertops and breakfast bar',
  },
  {
    id: 'img_psl01_05',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Second-floor master bedroom suite with attached luxury bathroom and private front balcony',
  },
  {
    id: 'img_psl01_06',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Well-proportioned guest bedroom with large casement windows and built-in wardrobes',
  },
  {
    id: 'img_psl01_07',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'European-fitted master bathroom with glass shower cubicle and centralized solar hot water',
  },
  {
    id: 'img_psl01_08',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'OUTDOOR_GARDEN',
    caption: 'Private landscaped lawn with flowering shrubs, boundary masonry wall, and outdoor lighting',
  },
  {
    id: 'img_psl01_09',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'PARKING_GARAGE',
    caption: 'Covered 2-vehicle porch with automated remote roller shutter gate and CCTV coverage',
  },
  {
    id: 'img_psl01_10',
    propertyId: 'prop_sl_01',
    url: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'FEATURE_IMAGE',
    caption: 'Rooftop 5kW solar net metering installation and overhead water storage tanks',
  },

  // prop_sl_02: Luxury Sea-View Apartment in Colombo 03 (APARTMENT, Kollupitiya)
  {
    id: 'img_psl02_01',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Striking modern luxury tower on Marine Drive, Kollupitiya with direct Indian Ocean frontage',
  },
  {
    id: 'img_psl02_02',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Expansive ocean-view living hall with acoustic double glazing and centralized inverter AC',
  },
  {
    id: 'img_psl02_03',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'OCEAN_BALCONY',
    caption: 'Panoramic ocean sunset balcony framing Colombo Port City and coastline',
  },
  {
    id: 'img_psl02_04',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Imported German kitchen pantry with built-in Siemens oven, microwave, and quartz counters',
  },
  {
    id: 'img_psl02_05',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Oceanfront master suite with expansive windows, walk-in closets, and timber flooring',
  },
  {
    id: 'img_psl02_06',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Spacious secondary en-suite bedroom with built-in storage and city horizon views',
  },
  {
    id: 'img_psl02_07',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Ensuite luxury bathroom featuring double vanities, marble tiling, and rainfall shower',
  },
  {
    id: 'img_psl02_08',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'INFINITY_POOL',
    caption: '25m rooftop infinity swimming pool overlooking the Indian Ocean and city skyline',
  },
  {
    id: 'img_psl02_09',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'FITNESS_CENTER',
    caption: 'Fully equipped residents fitness center with panoramic ocean workout vistas',
  },
  {
    id: 'img_psl02_10',
    propertyId: 'prop_sl_02',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Two allocated covered basement parking bays near high-speed elevator banks',
  },

  // prop_sl_03: Prime Residential Land Plot in Kaduwela (LAND, Colombo District)
  {
    id: 'img_psl03_01',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: '12-perch square block of elevated residential land in prime Kaduwela-Malabe corridor',
  },
  {
    id: 'img_psl03_02',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'ACCESS_ROAD',
    caption: 'Wide 20-foot carpeted roadway with concrete curbs and street lighting',
  },
  {
    id: 'img_psl03_03',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'BOUNDARY_WALL',
    caption: 'Completed masonry boundary walls defining clear plot borders on all sides',
  },
  {
    id: 'img_psl03_04',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'TOPOGRAPHY',
    caption: 'Firm, dry, elevated red gravel foundation ground ready for immediate construction',
  },
  {
    id: 'img_psl03_05',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'UTILITIES',
    caption: 'Three-phase CEB electricity connection and National Water Supply pipe line at site boundary',
  },
  {
    id: 'img_psl03_06',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'NEIGHBORHOOD',
    caption: 'Peaceful upscale residential enclave with luxury modern neighboring houses',
  },
  {
    id: 'img_psl03_07',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'DRAINAGE',
    caption: 'Engineered stormwater drainage trenches constructed along the road frontage',
  },
  {
    id: 'img_psl03_08',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SURROUNDINGS',
    caption: 'Lush greenery and coconut tree canopy creating a cooler microclimate',
  },
  {
    id: 'img_psl03_09',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1524813686514-a57563d77d66?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'TITLE_PLAN',
    caption: 'Bim Saviya First Class bank-cleared title plan and licensed surveyor survey report',
  },
  {
    id: 'img_psl03_10',
    propertyId: 'prop_sl_03',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'EXPRESSWAY_ACCESS',
    caption: 'Convenient 4-minute access road connecting directly to the Kaduwela Expressway Interchange',
  },

  // prop_sl_04: Colonial Heritage Beachfront Villa in Galle Fort (VILLA, Galle)
  {
    id: 'img_psl04_01',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: '18th-century Dutch colonial villa located inside UNESCO World Heritage Galle Fort',
  },
  {
    id: 'img_psl04_02',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'COURTYARD_POOL',
    caption: 'Central cobblestone courtyard with private emerald plunge pool and coral limestone walls',
  },
  {
    id: 'img_psl04_03',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'LIVING_HALL',
    caption: 'Grand living hall with high beamed ceilings, antique calamander wood furniture, and terracotta tiles',
  },
  {
    id: 'img_psl04_04',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'VERANDAH',
    caption: 'Shaded colonial verandah fitted with authentic antique ebony and rattan planter chairs',
  },
  {
    id: 'img_psl04_05',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Grand Dutch four-poster teak canopy bed, timber flooring, and shuttered courtyard windows',
  },
  {
    id: 'img_psl04_06',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Spacious guest bedroom with antique wardrobe and garden courtyard outlook',
  },
  {
    id: 'img_psl04_07',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Semi-open air rain shower bathroom with polished terrazzo and unlacquered brass fittings',
  },
  {
    id: 'img_psl04_08',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'DINING_ROOM',
    caption: 'Formal colonial dining room featuring a 10-seater restored antique jackwood table',
  },
  {
    id: 'img_psl04_09',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'KITCHEN',
    caption: 'Charming heritage kitchen with modern stainless steel appliances and polished cement counters',
  },
  {
    id: 'img_psl04_10',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'RAMPARTS_VIEW',
    caption: 'Upper-floor balcony looking out toward the historic Galle lighthouse and Indian Ocean ramparts',
  },
  {
    id: 'img_psl04_11',
    propertyId: 'prop_sl_04',
    url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'STREET_VIEW',
    caption: 'Charming street perspective along historic cobblestone Lighthouse Street in Galle Fort',
  },

  // prop_sl_05: Tropical Modern Family Home in Battaramulla (HOUSE, Colombo District)
  {
    id: 'img_psl05_01',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: 'Architect-designed tropical modern home in Pelawatta, Battaramulla with timber screens',
  },
  {
    id: 'img_psl05_02',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'DOUBLE_HEIGHT_LIVING',
    caption: 'Double-height living room with exposed Kumbuk timber ceiling and polished cement titanium floors',
  },
  {
    id: 'img_psl05_03',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'FLOATING_STAIRCASE',
    caption: 'Floating solid Kumbuk timber staircase with architectural stainless steel cabling',
  },
  {
    id: 'img_psl05_04',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'INNER_COURTYARD',
    caption: 'Internal Zen pebble courtyard bringing natural sunlight into the central living areas',
  },
  {
    id: 'img_psl05_05',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'DRY_PANTRY',
    caption: 'Minimalist dry kitchen pantry with white quartz waterfall island and bar seating',
  },
  {
    id: 'img_psl05_06',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'WET_KITCHEN',
    caption: 'Fully equipped stainless steel and granite wet kitchen for heavy cooking and meal prep',
  },
  {
    id: 'img_psl05_07',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'MASTER_BEDROOM',
    caption: 'Master suite with private balcony, titanium floors, and air-conditioning',
  },
  {
    id: 'img_psl05_08',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SECOND_BEDROOM',
    caption: 'Second bedroom with built-in teak wardrobe and modern ensuite bathroom',
  },
  {
    id: 'img_psl05_09',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'BATHROOM',
    caption: 'Open-to-sky shower garden with custom terrazzo vanity and rain showerhead',
  },
  {
    id: 'img_psl05_10',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1519643381401-22c77e60520e?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'ROOFTOP_TERRACE',
    caption: 'Rooftop entertaining terrace overlooking the lush greenery of Battaramulla',
  },
  {
    id: 'img_psl05_11',
    propertyId: 'prop_sl_05',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 10,
    category: 'PARKING_GARAGE',
    caption: 'Two-vehicle covered garage with automated remote roller shutter and high boundary wall',
  },

  // prop_sl_06: Panoramic Golf & Lake View Condominium in Rajagiriya (CONDO, Colombo District)
  {
    id: 'img_psl06_01',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 1,
    displayOrder: 0,
    category: 'HERO_EXTERIOR',
    caption: '14th-floor corner luxury condo overlooking Royal Colombo Golf Club greens in Rajagiriya',
  },
  {
    id: 'img_psl06_02',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 1,
    category: 'LIVING_ROOM',
    caption: 'Sun-filled corner living lounge with engineered teak flooring and panoramic golf course views',
  },
  {
    id: 'img_psl06_03',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 2,
    category: 'VIEWING_TERRACE',
    caption: 'Expansive private terrace looking across the Diyawanna Lake bird sanctuary and golf greens',
  },
  {
    id: 'img_psl06_04',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 3,
    category: 'KITCHEN',
    caption: 'Contemporary kitchen with centralized LP gas pipeline, granite counters, and pantry cabinets',
  },
  {
    id: 'img_psl06_05',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 4,
    category: 'MASTER_BEDROOM',
    caption: 'Corner master bedroom with wall-to-wall glass framing golf club fairways and sunrise',
  },
  {
    id: 'img_psl06_06',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 5,
    category: 'SECOND_BEDROOM',
    caption: 'Second bedroom with built-in cupboards, engineered timber flooring, and lake view',
  },
  {
    id: 'img_psl06_07',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 6,
    category: 'BATHROOM',
    caption: 'Contemporary bathroom with frameless glass walk-in shower and stone floating vanity',
  },
  {
    id: 'img_psl06_08',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 7,
    category: 'SWIMMING_POOL',
    caption: 'Olympic-length swimming pool and landscaped sun deck located on the residential podium',
  },
  {
    id: 'img_psl06_09',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 8,
    category: 'GYM_CLUBHOUSE',
    caption: 'Residents modern gymnasium and air-conditioned community clubhouse',
  },
  {
    id: 'img_psl06_10',
    propertyId: 'prop_sl_06',
    url: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=80',
    isPrimary: 0,
    displayOrder: 9,
    category: 'PARKING_GARAGE',
    caption: 'Allocated covered parking space in secure multi-tier parking facility with 24/7 guard',
  },
];
