package com.nexus.property.feedback;
import com.nexus.property.auth.*;import com.nexus.property.core.*;import jakarta.servlet.http.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/feedback") public class FeedbackController{
 private final Db db;public FeedbackController(Db db){this.db=db;}private String ticket(){return "TKT-"+System.currentTimeMillis()+"-"+(100+new Random().nextInt(900));}
 private Map<String,Object> rating(Map<String,Object>r){var m=new LinkedHashMap<String,Object>();m.put("id",Rows.s(r,"id"));m.put("propertyId",Rows.s(r,"property_id"));m.put("customerId",Rows.s(r,"customer_id"));m.put("customerName",Rows.s(r,"customer_name"));m.put("score",Rows.l(r,"score"));m.put("comment",Rows.s(r,"comment"));m.put("createdAt",Rows.l(r,"created_at"));m.put("updatedAt",Rows.l(r,"updated_at"));return m;}
 @PostMapping("/ratings") @ResponseStatus(HttpStatus.CREATED)public Map<String,Object>rate(HttpServletRequest r,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);String pid=Objects.toString(b.get("propertyId"),"");int score=((Number)b.getOrDefault("score",0)).intValue();if(score<1||score>5)throw Api.error(400,"Rating score must be between 1 and 5.");var ex=db.one("SELECT id FROM ratings WHERE property_id=? AND customer_id=?",pid,u.userId());long n=System.currentTimeMillis();if(ex==null)db.exec("INSERT INTO ratings(id,property_id,customer_id,score,comment,created_at,updated_at) VALUES(?,?,?,?,?,?,?)",db.uuid(),pid,u.userId(),score,b.get("comment"),n,n);else db.exec("UPDATE ratings SET score=?,comment=?,updated_at=? WHERE id=?",score,b.get("comment"),n,Rows.s(ex,"id"));var row=db.one("SELECT r.*,u.full_name customer_name FROM ratings r JOIN users u ON u.id=r.customer_id WHERE r.property_id=? AND r.customer_id=?",pid,u.userId());return Api.ok("Rating saved successfully.",rating(row));}
 @GetMapping("/ratings/property/{propertyId}")public Map<String,Object>ratings(@PathVariable String propertyId){var list=db.all("SELECT r.*,u.full_name customer_name FROM ratings r JOIN users u ON u.id=r.customer_id WHERE property_id=? ORDER BY created_at DESC",propertyId).stream().map(this::rating).toList();double avg=list.stream().mapToDouble(x->((Number)x.get("score")).doubleValue()).average().orElse(0);return Api.ok(Map.of("ratings",list,"averageRating",Math.round(avg*10)/10.0,"count",list.size()));}
 @GetMapping("/ratings/my")public Map<String,Object>my(HttpServletRequest r){var u=AuthFilter.require(r);return Api.ok(db.all("SELECT r.*,u.full_name customer_name FROM ratings r JOIN users u ON u.id=r.customer_id WHERE customer_id=? ORDER BY created_at DESC",u.userId()).stream().map(this::rating).toList());}
 @DeleteMapping("/ratings/{id}")public Map<String,Object>del(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.require(r);int n="ADMIN".equals(u.role())?db.exec("DELETE FROM ratings WHERE id=?",id):db.exec("DELETE FROM ratings WHERE id=? AND customer_id=?",id,u.userId());if(n==0)throw Api.error(404,"Rating not found.");return Api.message("Rating deleted successfully.");}
 @PostMapping("/inquiries") @ResponseStatus(HttpStatus.CREATED)public Map<String,Object>inq(HttpServletRequest r,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);String id=db.uuid();long n=System.currentTimeMillis();db.exec("INSERT INTO inquiries(id,ticket_id,property_id,customer_id,assigned_agent_id,subject,message,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",id,ticket(),b.get("propertyId"),u.userId(),b.get("assignedAgentId"),b.getOrDefault("subject","Property inquiry"),b.getOrDefault("message",""),"NEW",n,n);return Api.ok("Inquiry submitted successfully.",inquiry(db.one(inquirySql()+" WHERE i.id=?",id)));}
 @GetMapping("/inquiries")public Map<String,Object>inquiries(HttpServletRequest r){var u=AuthFilter.require(r);String where="ADMIN".equals(u.role())?"":" WHERE "+("AGENT".equals(u.role())?"i.assigned_agent_id":"i.customer_id")+"=?";var rows="ADMIN".equals(u.role())?db.all(inquirySql()+where+" ORDER BY i.created_at DESC"):db.all(inquirySql()+where+" ORDER BY i.created_at DESC",u.userId());return Api.ok("Inquiries retrieved.",rows.stream().map(this::inquiry).toList());}
 @GetMapping("/inquiries/{id}")public Map<String,Object>inquiryOne(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.require(r);var x=db.one(inquirySql()+" WHERE i.id=?",id);if(x==null)throw Api.error(404,"Inquiry not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(x,"customer_id"))&&!u.userId().equals(Rows.s(x,"assigned_agent_id")))throw Api.error(403,"Access forbidden.");return Api.ok("Inquiry retrieved.",inquiry(x));}
 @PostMapping("/inquiries/{id}/respond")public Map<String,Object>respond(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){AuthFilter.role(r,"AGENT","ADMIN");String response=Objects.toString(b.get("response"),"").trim();if(response.isBlank())throw Api.error(400,"Response is required.");db.exec("UPDATE inquiries SET response=?,status=?,updated_at=? WHERE id=?",response,Objects.toString(b.getOrDefault("status","RESOLVED")),System.currentTimeMillis(),id);return Api.ok("Inquiry response saved.",inquiry(db.one(inquirySql()+" WHERE i.id=?",id)));}
 @PostMapping("/complaints") @ResponseStatus(HttpStatus.CREATED)public Map<String,Object>complaint(HttpServletRequest r,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);String id=db.uuid();long n=System.currentTimeMillis();db.exec("INSERT INTO complaints(id,ticket_id,property_id,customer_id,subject,description,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)",id,ticket(),b.get("propertyId"),u.userId(),b.getOrDefault("subject","Complaint"),b.getOrDefault("description",b.getOrDefault("message","")),"NEW",n,n);return Api.ok("Complaint submitted successfully.",complaintMap(db.one(complaintSql()+" WHERE c.id=?",id)));}
 @GetMapping("/complaints")public Map<String,Object>complaints(HttpServletRequest r){var u=AuthFilter.require(r);var rows="ADMIN".equals(u.role())||"AGENT".equals(u.role())?db.all(complaintSql()+" ORDER BY c.created_at DESC"):db.all(complaintSql()+" WHERE c.customer_id=? ORDER BY c.created_at DESC",u.userId());return Api.ok("Complaints retrieved.",rows.stream().map(this::complaintMap).toList());}
 @GetMapping("/complaints/{id}")public Map<String,Object>complaintOne(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.require(r);var x=db.one(complaintSql()+" WHERE c.id=?",id);if(x==null)throw Api.error(404,"Complaint not found.");if(!Set.of("ADMIN","AGENT").contains(u.role())&&!u.userId().equals(Rows.s(x,"customer_id")))throw Api.error(403,"Access forbidden.");return Api.ok("Complaint retrieved.",complaintMap(x));}
 @PostMapping("/complaints/{id}/resolve")public Map<String,Object>resolve(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){AuthFilter.role(r,"AGENT","ADMIN");db.exec("UPDATE complaints SET resolution=?,status=?,updated_at=? WHERE id=?",b.get("resolution"),b.getOrDefault("status","RESOLVED"),System.currentTimeMillis(),id);return Api.ok("Complaint resolution saved.",complaintMap(db.one(complaintSql()+" WHERE c.id=?",id)));}
 private String inquirySql(){return "SELECT i.*,p.title property_title,c.full_name customer_name,a.full_name agent_name FROM inquiries i JOIN properties p ON p.id=i.property_id JOIN users c ON c.id=i.customer_id LEFT JOIN users a ON a.id=i.assigned_agent_id";}private Map<String,Object>inquiry(Map<String,Object>r){var m=new LinkedHashMap<String,Object>();for(String k:List.of("id","ticket_id","property_id","property_title","customer_id","customer_name","assigned_agent_id","agent_name","subject","message","status","response"))m.put(camel(k),Rows.s(r,k));m.put("createdAt",Rows.l(r,"created_at"));m.put("updatedAt",Rows.l(r,"updated_at"));return m;}private String complaintSql(){return "SELECT c.*,p.title property_title,u.full_name customer_name FROM complaints c LEFT JOIN properties p ON p.id=c.property_id JOIN users u ON u.id=c.customer_id";}private Map<String,Object>complaintMap(Map<String,Object>r){var m=new LinkedHashMap<String,Object>();for(String k:List.of("id","ticket_id","property_id","property_title","customer_id","customer_name","subject","description","status","resolution"))m.put(camel(k),Rows.s(r,k));m.put("createdAt",Rows.l(r,"created_at"));m.put("updatedAt",Rows.l(r,"updated_at"));return m;}private String camel(String s){String[]p=s.split("_");StringBuilder z=new StringBuilder(p[0]);for(int i=1;i<p.length;i++)z.append(Character.toUpperCase(p[i].charAt(0))).append(p[i].substring(1));return z.toString();}}
