package com.nexus.property.property;
import com.nexus.property.auth.*;import com.nexus.property.core.*;import jakarta.servlet.http.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/properties") public class PropertyController{
 private final Db db;public PropertyController(Db db){this.db=db;}
 private static final Set<String>TYPES=Set.of("HOUSE","APARTMENT","CONDO","VILLA","LAND","COMMERCIAL"),STAT=Set.of("DRAFT","PENDING_APPROVAL","ACTIVE","UNDER_CONTRACT","SOLD","RENTED","ARCHIVED");
 private String baseSelect(){return "SELECT p.*,u.full_name owner_name,u.email owner_email,u.phone owner_phone,(SELECT url FROM property_images WHERE property_id=p.id ORDER BY is_primary DESC,display_order ASC LIMIT 1) primary_image,(SELECT AVG(score) FROM ratings WHERE property_id=p.id) avg_score,(SELECT COUNT(*) FROM ratings WHERE property_id=p.id) rating_count FROM properties p JOIN users u ON u.id=p.owner_id";}
 @GetMapping("/media/config")public Map<String,Object> config(){return Api.ok(Map.of("maxImagesPerProperty",15,"maxFileSizePerImageBytes",10*1024*1024,"maxFileSizeMB",10,"maxTotalBatchSizeMB",30,"allowedFormats",List.of("jpg","jpeg","png","webp"),"allowedMimeTypes",List.of("image/jpeg","image/png","image/webp")));}
 @GetMapping public Map<String,Object> search(HttpServletRequest r,@RequestParam Map<String,String>q){var u=AuthFilter.user(r);int page=Math.max(1,Integer.parseInt(q.getOrDefault("page","1"))),size=Math.min(50,Math.max(1,Integer.parseInt(q.getOrDefault("size","12")))),off=(page-1)*size;StringBuilder w=new StringBuilder(" WHERE 1=1");List<Object>a=new ArrayList<>();if(u==null||"CUSTOMER".equals(u.role()))w.append(" AND p.status='ACTIVE'");else if(q.containsKey("status")&&!"ALL".equals(q.get("status"))&&STAT.contains(q.get("status"))){w.append(" AND p.status=?");a.add(q.get("status"));}if(q.containsKey("keyword")&&!q.get("keyword").isBlank()){String t="%"+q.get("keyword").toLowerCase()+"%";w.append(" AND (LOWER(p.title) LIKE ? OR LOWER(p.description) LIKE ? OR LOWER(p.location) LIKE ? OR LOWER(p.amenities) LIKE ?)");a.add(t);a.add(t);a.add(t);a.add(t);}if(q.containsKey("location")&&!q.get("location").isBlank()){w.append(" AND LOWER(p.location) LIKE ?");a.add("%"+q.get("location").toLowerCase()+"%");}if(q.containsKey("propertyType")&&TYPES.contains(q.get("propertyType"))){w.append(" AND p.property_type=?");a.add(q.get("propertyType"));}if(q.containsKey("minPrice")){w.append(" AND p.price>=?");a.add(Double.parseDouble(q.get("minPrice")));}if(q.containsKey("maxPrice")){w.append(" AND p.price<=?");a.add(Double.parseDouble(q.get("maxPrice")));}if(q.containsKey("bedrooms")){w.append(" AND p.bedrooms>=?");a.add(Integer.parseInt(q.get("bedrooms")));}if(q.containsKey("amenities"))for(String x:q.get("amenities").split(",")){w.append(" AND LOWER(p.amenities) LIKE ?");a.add("%"+x.trim().toLowerCase()+"%");}String sort=switch(q.getOrDefault("sortBy","createdAt")){case"price"->"p.price";case"bedrooms"->"p.bedrooms";case"area"->"p.area";case"location"->"p.location";case"title"->"p.title";default->"p.created_at";},dir="ASC".equalsIgnoreCase(q.get("sortOrder"))?"ASC":"DESC";long total=db.scalarLong("SELECT COUNT(*) FROM properties p"+w,a.toArray());var aa=new ArrayList<>(a);aa.add(size);aa.add(off);var content=db.all(baseSelect()+w+" ORDER BY "+sort+" "+dir+" LIMIT ? OFFSET ?",aa.toArray()).stream().map(PropertyMapper::map).toList();return Api.ok("Properties retrieved successfully.",Map.of("content",content,"page",page,"size",size,"totalElements",total,"totalPages",(int)Math.ceil(total/(double)size),"first",page==1,"last",page>=Math.ceil(total/(double)size)));}
 @GetMapping("/owner/my-listings")public Map<String,Object> mine(HttpServletRequest r){var u=AuthFilter.role(r,"PROPERTY_OWNER","ADMIN");String sql=baseSelect()+("ADMIN".equals(u.role())?"":" WHERE p.owner_id=?")+" ORDER BY p.created_at DESC";var rows="ADMIN".equals(u.role())?db.all(sql):db.all(sql,u.userId());return Api.ok("Owner properties retrieved.",rows.stream().map(PropertyMapper::map).toList());}
 @GetMapping("/user/recently-viewed")public Map<String,Object> recent(HttpServletRequest r){var u=AuthFilter.require(r);var rows=db.all(baseSelect()+" JOIN recently_viewed_properties rv ON rv.property_id=p.id WHERE rv.user_id=? ORDER BY rv.viewed_at DESC LIMIT 8",u.userId());return Api.ok("Recently viewed properties retrieved.",rows.stream().map(PropertyMapper::map).toList());}
 @PostMapping("/{id}/view")public Map<String,Object> view(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.user(r);if(u!=null){db.exec("INSERT INTO recently_viewed_properties(id,user_id,property_id,viewed_at) VALUES(?,?,?,?) ON CONFLICT(user_id,property_id) DO UPDATE SET viewed_at=excluded.viewed_at",db.uuid(),u.userId(),id,System.currentTimeMillis());}return Api.ok(null);}
 @GetMapping("/{id}")public Map<String,Object> one(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.user(r);var row=db.one(baseSelect()+" WHERE p.id=?",id);if(row==null)throw Api.error(404,"Property not found.");if(!"ACTIVE".equals(Rows.s(row,"status"))&&(u==null||(!"ADMIN".equals(u.role())&&!Objects.equals(u.userId(),Rows.s(row,"owner_id")))))throw Api.error(403,"This property is not publicly available.");var m=PropertyMapper.map(row);m.put("images",images(id));if(u!=null)view(r,id);return Api.ok("Property details retrieved.",m);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED)public Map<String,Object> create(HttpServletRequest r,@RequestBody Map<String,Object>b){var u=AuthFilter.role(r,"PROPERTY_OWNER","ADMIN");validate(b,true);String id=db.uuid();long now=System.currentTimeMillis();String status=Objects.toString(b.getOrDefault("status","DRAFT"));if(!STAT.contains(status))status="DRAFT";db.exec("INSERT INTO properties(id,owner_id,title,description,property_type,location,price,bedrooms,bathrooms,area,amenities,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,u.userId(),b.get("title"),b.get("description"),b.get("propertyType"),b.get("location"),num(b.get("price")),integer(b.getOrDefault("bedrooms",0)),integer(b.getOrDefault("bathrooms",1)),num(b.get("area")),Rows.json(b.getOrDefault("amenities",List.of())),status,now,now);if(b.get("images") instanceof List<?> list)for(Object x:list)if(x!=null)addImage(id,x.toString(),false);audit(u.userId(),"PROPERTY_CREATED","PROPERTY",id,"Created property");return one(r,id);}
 @PutMapping("/{id}")public Map<String,Object> update(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);var p=db.one("SELECT * FROM properties WHERE id=?",id);if(p==null)throw Api.error(404,"Property not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(p,"owner_id")))throw Api.error(403,"Access forbidden: You do not have permission to modify this property.");var fields=new LinkedHashMap<String,String>();fields.put("title","title");fields.put("description","description");fields.put("propertyType","property_type");fields.put("location","location");fields.put("price","price");fields.put("bedrooms","bedrooms");fields.put("bathrooms","bathrooms");fields.put("area","area");fields.put("status","status");List<String>s=new ArrayList<>();List<Object>a=new ArrayList<>();for(var e:fields.entrySet())if(b.containsKey(e.getKey())){if("status".equals(e.getKey()))transition(Rows.s(p,"status"),Objects.toString(b.get("status")),u.role());s.add(e.getValue()+"=?");a.add(b.get(e.getKey()));}if(b.containsKey("amenities")){s.add("amenities=?");a.add(Rows.json(b.get("amenities")));}if(!s.isEmpty()){s.add("updated_at=?");a.add(System.currentTimeMillis());a.add(id);db.exec("UPDATE properties SET "+String.join(",",s)+" WHERE id=?",a.toArray());}audit(u.userId(),"PROPERTY_UPDATED","PROPERTY",id,"Updated property");return one(r,id);}
 @DeleteMapping("/{id}")public Map<String,Object> delete(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.require(r);var p=db.one("SELECT * FROM properties WHERE id=?",id);if(p==null)throw Api.error(404,"Property not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(p,"owner_id")))throw Api.error(403,"Access forbidden: You do not have permission to delete this property.");if(db.one("SELECT id FROM appointments WHERE property_id=? AND status IN ('REQUESTED','CONFIRMED')",id)!=null)throw Api.error(400,"Cannot delete property with active viewing appointments.");db.exec("DELETE FROM properties WHERE id=?",id);audit(u.userId(),"PROPERTY_DELETED","PROPERTY",id,"Deleted property");return Api.message("Property deleted successfully.");}
 @PostMapping("/{id}/approve")public Map<String,Object> approve(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){var u=AuthFilter.role(r,"ADMIN");boolean approved=Boolean.TRUE.equals(b.get("approved"));var p=db.one("SELECT owner_id,title FROM properties WHERE id=?",id);if(p==null)throw Api.error(404,"Property not found.");db.exec("UPDATE properties SET status=?,updated_at=? WHERE id=?",approved?"ACTIVE":"DRAFT",System.currentTimeMillis(),id);notify(Rows.s(p,"owner_id"),approved?"PROPERTY_APPROVED":"PROPERTY_REJECTED",approved?"Listing Approved":"Listing Requires Updates",approved?"Your listing has been approved and is now active.":"Your listing requires updates.",id);audit(u.userId(),approved?"PROPERTY_APPROVED":"PROPERTY_REJECTED","PROPERTY",id,"Admin approval action");return Api.message("Property "+(approved?"approved and made active":"rejected and returned to draft")+".");}
 @PostMapping("/media/upload-temp")public Map<String,Object> temp(HttpServletRequest r,@RequestBody Map<String,Object>b){AuthFilter.require(r);String data=Objects.toString(b.getOrDefault("dataUrl",b.getOrDefault("base64","")));if(data.isBlank())throw Api.error(400,"Image data is required.");return Api.ok("Temporary media file uploaded successfully.",Map.of("url",data,"temp",true));}
 @PostMapping("/{id}/images") @ResponseStatus(HttpStatus.CREATED)public Map<String,Object> image(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){checkOwner(r,id);String url=Objects.toString(b.getOrDefault("imageUrl",b.getOrDefault("dataUrl",b.getOrDefault("base64",""))));var im=addImage(id,url,Boolean.TRUE.equals(b.get("isPrimary")));return Api.ok("Property image added successfully.",im);}
 @PostMapping("/{id}/images/upload")public Map<String,Object> upload(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){return image(r,id,b);}
 @PostMapping("/{id}/images/batch-upload")public Map<String,Object> batch(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){checkOwner(r,id);List<Map<String,Object>>out=new ArrayList<>();Object v=b.get("images");if(v instanceof List<?> l)for(Object x:l){String url=x instanceof Map<?,?>mm?Objects.toString(mm.get("dataUrl"),Objects.toString(mm.get("base64"),"")):Objects.toString(x,"");if(!url.isBlank())out.add(addImage(id,url,false));}return Api.ok("Images uploaded successfully.",out);}
 @PutMapping("/{id}/images/reorder")public Map<String,Object> reorder(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){checkOwner(r,id);if(b.get("imageIds") instanceof List<?>l){int i=0;for(Object x:l)db.exec("UPDATE property_images SET display_order=? WHERE id=? AND property_id=?",i++,x,id);}return Api.ok("Images reordered successfully.",images(id));}
 @PutMapping("/{id}/images/{imageId}/replace")public Map<String,Object> replace(HttpServletRequest r,@PathVariable String id,@PathVariable String imageId,@RequestBody Map<String,Object>b){checkOwner(r,id);String url=Objects.toString(b.getOrDefault("dataUrl",b.getOrDefault("base64",b.getOrDefault("imageUrl",""))));db.exec("UPDATE property_images SET url=? WHERE id=? AND property_id=?",url,imageId,id);return Api.ok("Image replaced successfully.",imageMap(db.one("SELECT * FROM property_images WHERE id=?",imageId)));}
 @PutMapping("/{id}/images/{imageId}/primary")public Map<String,Object> primary(HttpServletRequest r,@PathVariable String id,@PathVariable String imageId){checkOwner(r,id);db.exec("UPDATE property_images SET is_primary=0 WHERE property_id=?",id);db.exec("UPDATE property_images SET is_primary=1 WHERE id=? AND property_id=?",imageId,id);return Api.ok("Primary image updated.",imageMap(db.one("SELECT * FROM property_images WHERE id=?",imageId)));}
 @DeleteMapping("/{id}/images/{imageId}")public Map<String,Object> delImage(HttpServletRequest r,@PathVariable String id,@PathVariable String imageId){checkOwner(r,id);db.exec("DELETE FROM property_images WHERE id=? AND property_id=?",imageId,id);return Api.message("Property image deleted successfully.");}
 @GetMapping("/{id}/photo-specs")public Map<String,Object> specs(@PathVariable String id){var p=db.one("SELECT * FROM properties WHERE id=?",id);if(p==null)throw Api.error(404,"Property not found.");return Api.ok(Map.of("propertyId",id,"title",Rows.s(p,"title"),"recommendedCount",10,"categories",List.of("exterior","living room","bedroom","bathroom","kitchen","amenities","neighborhood"),"guidance","Use realistic images consistent with the listing details."));}
 @PostMapping("/{id}/generate-images")public Map<String,Object> generated(HttpServletRequest r,@PathVariable String id,@RequestBody(required=false)Map<String,Object>b){checkOwner(r,id);return Api.ok("Image generation request accepted. Existing Java backend preserves the endpoint; configure GEMINI_API_KEY/image provider to generate new media.",Map.of("propertyId",id,"images",images(id)));}
 private void validate(Map<String,Object>b,boolean create){for(String k:List.of("title","description","propertyType","location","price","area"))if(create&&!b.containsKey(k))throw Api.error(400,k+" is required.");if(b.containsKey("propertyType")&&!TYPES.contains(Objects.toString(b.get("propertyType"))))throw Api.error(400,"Invalid property type.");}
 private Number num(Object x){return x instanceof Number n?n:Double.parseDouble(Objects.toString(x,"0"));}private int integer(Object x){return x instanceof Number n?n.intValue():Integer.parseInt(Objects.toString(x,"0"));}
 private void transition(String from,String to,String role){if(from.equals(to)||"ADMIN".equals(role))return;boolean ok="PROPERTY_OWNER".equals(role)&&((from.equals("DRAFT")&&to.equals("PENDING_APPROVAL"))||(from.equals("ACTIVE")&&(to.equals("UNDER_CONTRACT")||to.equals("ARCHIVED")))||(from.equals("UNDER_CONTRACT")&&(to.equals("ACTIVE")||to.equals("SOLD")||to.equals("RENTED"))));if(!ok)throw Api.error(400,"Invalid status transition from "+from+" to "+to+" for "+role+".");}
 private void checkOwner(HttpServletRequest r,String id){var u=AuthFilter.require(r);var p=db.one("SELECT owner_id FROM properties WHERE id=?",id);if(p==null)throw Api.error(404,"Property not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(p,"owner_id")))throw Api.error(403,"Access forbidden.");}
 private List<Map<String,Object>>images(String id){return db.all("SELECT * FROM property_images WHERE property_id=? ORDER BY is_primary DESC,display_order,id",id).stream().map(this::imageMap).toList();}
 private Map<String,Object>imageMap(Map<String,Object>r){if(r==null)return Map.of();var m=new LinkedHashMap<String,Object>();m.put("id",Rows.s(r,"id"));m.put("propertyId",Rows.s(r,"property_id"));m.put("url",Rows.s(r,"url"));m.put("isPrimary",Rows.b(r,"is_primary"));m.put("displayOrder",Rows.l(r,"display_order"));m.put("caption",Rows.s(r,"caption"));m.put("category",Rows.s(r,"category"));m.put("createdAt",Rows.l(r,"created_at"));return m;}
 private Map<String,Object>addImage(String id,String url,boolean primary){if(url==null||url.isBlank())throw Api.error(400,"Image URL or data is required.");if(db.scalarLong("SELECT COUNT(*) FROM property_images WHERE property_id=?",id)>=15)throw Api.error(400,"Maximum 15 images per property.");String iid=db.uuid();long order=db.scalarLong("SELECT COUNT(*) FROM property_images WHERE property_id=?",id);if(primary)db.exec("UPDATE property_images SET is_primary=0 WHERE property_id=?",id);db.exec("INSERT INTO property_images(id,property_id,url,is_primary,display_order,created_at) VALUES(?,?,?,?,?,?)",iid,id,url,primary?1:0,order,System.currentTimeMillis());return imageMap(db.one("SELECT * FROM property_images WHERE id=?",iid));}
 private void notify(String uid,String type,String title,String msg,String ref){db.exec("INSERT INTO notifications(id,user_id,type,title,message,reference_id,is_read,created_at) VALUES(?,?,?,?,?,?,0,?)",db.uuid(),uid,type,title,msg,ref,System.currentTimeMillis());}
 private void audit(String actor,String action,String type,String id,String details){db.exec("INSERT INTO audit_logs(id,actor_id,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,?,?)",db.uuid(),actor,action,type,id,details,System.currentTimeMillis());}
}
