package com.nexus.property.appointment;
import com.nexus.property.auth.*;import com.nexus.property.core.*;import jakarta.servlet.http.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/appointments") public class AppointmentController{
 private final Db db;public AppointmentController(Db db){this.db=db;}
 private String sel(){return "SELECT a.*,p.title property_title,p.location property_location,c.full_name customer_name,ag.full_name agent_name FROM appointments a JOIN properties p ON p.id=a.property_id JOIN users c ON c.id=a.customer_id JOIN users ag ON ag.id=a.agent_id";}
 private Map<String,Object> map(Map<String,Object>r){var m=new LinkedHashMap<String,Object>();for(String k:List.of("id","status","notes","cancellation_reason"))m.put(camel(k),Rows.s(r,k));m.put("propertyId",Rows.s(r,"property_id"));m.put("propertyTitle",Rows.s(r,"property_title"));m.put("propertyLocation",Rows.s(r,"property_location"));m.put("customerId",Rows.s(r,"customer_id"));m.put("customerName",Rows.s(r,"customer_name"));m.put("agentId",Rows.s(r,"agent_id"));m.put("agentName",Rows.s(r,"agent_name"));m.put("appointmentTime",Rows.l(r,"appointment_time"));m.put("durationMinutes",Rows.l(r,"duration_minutes"));m.put("createdAt",Rows.l(r,"created_at"));m.put("updatedAt",Rows.l(r,"updated_at"));return m;}private String camel(String s){return switch(s){case"cancellation_reason"->"cancellationReason";default->s;};}
 @GetMapping("/meta/agents")public Map<String,Object> agents(){var x=db.all("SELECT id,full_name,email,phone FROM users WHERE role='AGENT' AND enabled=1 ORDER BY full_name").stream().map(r->Map.of("id",Rows.s(r,"id"),"fullName",Rows.s(r,"full_name"),"email",Rows.s(r,"email"),"phone",Objects.toString(Rows.s(r,"phone"),""))).toList();return Api.ok("Available agents retrieved.",x);}
 @GetMapping public Map<String,Object> list(HttpServletRequest r,@RequestParam(required=false)String status){var u=AuthFilter.require(r);String col="AGENT".equals(u.role())?"a.agent_id":"CUSTOMER".equals(u.role())?"a.customer_id":null;StringBuilder q=new StringBuilder(sel()+" WHERE 1=1");List<Object>a=new ArrayList<>();if(col!=null){q.append(" AND ").append(col).append("=?");a.add(u.userId());}if(status!=null&&!status.isBlank()&&!"ALL".equals(status)){q.append(" AND a.status=?");a.add(status);}q.append(" ORDER BY a.appointment_time DESC");return Api.ok("Appointments retrieved successfully.",db.all(q.toString(),a.toArray()).stream().map(this::map).toList());}
 @PostMapping @ResponseStatus(HttpStatus.CREATED)public Map<String,Object> create(HttpServletRequest r,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);if(!Set.of("CUSTOMER","ADMIN").contains(u.role()))throw Api.error(403,"Only customers can book viewing appointments.");String pid=Objects.toString(b.get("propertyId"),""),aid=Objects.toString(b.get("agentId"),"");long at=((Number)b.getOrDefault("appointmentTime",0)).longValue();int dur=((Number)b.getOrDefault("durationMinutes",60)).intValue();if(pid.isBlank()||aid.isBlank()||at<=System.currentTimeMillis())throw Api.error(400,"Property, agent and a future appointment time are required.");long end=at+dur*60000L;var conflict=db.one("SELECT id FROM appointments WHERE agent_id=? AND status IN ('REQUESTED','CONFIRMED','RESCHEDULED') AND appointment_time < ? AND appointment_time + duration_minutes*60000 > ?",aid,end,at);if(conflict!=null)throw Api.error(409,"The selected agent already has an appointment during this time.");String id=db.uuid();long now=System.currentTimeMillis();db.exec("INSERT INTO appointments(id,property_id,customer_id,agent_id,appointment_time,duration_minutes,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",id,pid,u.userId(),aid,at,dur,"REQUESTED",b.get("notes"),now,now);return Api.ok("Viewing appointment requested successfully.",map(db.one(sel()+" WHERE a.id=?",id)));}
 @GetMapping("/{id}")public Map<String,Object> one(HttpServletRequest r,@PathVariable String id){var u=AuthFilter.require(r);var x=db.one(sel()+" WHERE a.id=?",id);if(x==null)throw Api.error(404,"Appointment not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(x,"customer_id"))&&!u.userId().equals(Rows.s(x,"agent_id")))throw Api.error(403,"Access forbidden.");return Api.ok("Appointment details retrieved.",map(x));}
 @PostMapping("/{id}/action")public Map<String,Object> action(HttpServletRequest r,@PathVariable String id,@RequestBody Map<String,Object>b){var u=AuthFilter.require(r);var x=db.one("SELECT * FROM appointments WHERE id=?",id);if(x==null)throw Api.error(404,"Appointment not found.");if(!"ADMIN".equals(u.role())&&!u.userId().equals(Rows.s(x,"customer_id"))&&!u.userId().equals(Rows.s(x,"agent_id")))throw Api.error(403,"Access forbidden.");String ac=Objects.toString(b.get("action"),"").toUpperCase();String st=switch(ac){case"CONFIRM"->"CONFIRMED";case"CANCEL"->"CANCELLED";case"COMPLETE"->"COMPLETED";case"RESCHEDULE"->"RESCHEDULED";default->throw Api.error(400,"Unsupported appointment action.");};if("RESCHEDULED".equals(st)){long t=((Number)b.getOrDefault("rescheduledTime",0)).longValue();if(t<=System.currentTimeMillis())throw Api.error(400,"A future rescheduled time is required.");db.exec("UPDATE appointments SET appointment_time=?,status=?,updated_at=? WHERE id=?",t,st,System.currentTimeMillis(),id);}else db.exec("UPDATE appointments SET status=?,cancellation_reason=?,updated_at=? WHERE id=?",st,b.get("reason"),System.currentTimeMillis(),id);return Api.ok("Appointment successfully updated.",map(db.one(sel()+" WHERE a.id=?",id)));}
}
